spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teamactivity?&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: false
mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.lgy.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8088
  servlet:
    session:
      cookie:
        name:
logging:
  level:
    org.springframework.security: debug